stages:
  - verify
  - build
  - publish

services:
  - docker:19.03.12-dind
image: usvc/ci-docker:ea51c3b2
before_script:
  - apk add --no-cache git make

lint:
  stage: verify
  script:
    - make lint

build:
  stage: build
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ./images
  artifacts:
    expire_in: 1 week
    paths:
      - ./images
  script:
    - make build
    - make test
    - make scan
    - make export

publish:
  stage: publish
  dependencies: [build]
  script:
    - make import
    - docker login ${DOCKER_REGISTRY_URL} -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASSWORD}
    - make publish
  after_script:
    - docker logout
