apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yaml: |
    app:
      port: {{ .Values.config.app.port }}
      env: {{ .Values.config.app.env }}
      global-timeout: {{ .Values.config.app.globalTimeout }}
      log-level: {{ .Values.config.app.logLevel }}
    s3:
      keyId: ${S3_KEY_ID}
      accessId: ${S3_ACCESS_ID}
      region: {{ .Values.config.s3.region }}
